name: Go

on:
  push:
    branches: [ main, cli ]
  pull_request:
    branches: [ main, cli ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up libpcap
      run: sudo apt install libpcap-dev
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

