name: Release gocapture

on: release
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: gocapture ${{ github.ref }}
          draft: false
          prerelease: false
  linuxbuild:
    name: build gocapture
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install libpcap
        run: sudo apt-get install libpcap-dev
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build linux version
        run: go build -o gocapture_linux -v ./...
      - name: package
        run: sudo ./build.sh
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: gocapture_linux.tgz
          asset_name: gocapture_linux.tgz
          asset_content_type: application/gzip
  windowsbuild:
    runs-on: windows-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build windows version
        run: go build -v -o gocapture_windows.exe ./...
      - name: package
        run: ./build.cmd
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: gocapture_windows.tgz
          asset_name: gocapture_windows.tgz
          asset_content_type: application/gzip
